# Generated by Django 4.2.9 on 2024-01-19 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dislikes",
                    models.ManyToManyField(blank=True, related_name="faq_dislikes", to=settings.AUTH_USER_MODEL),
                ),
                ("likes", models.ManyToManyField(blank=True, related_name="faq_likes", to=settings.AUTH_USER_MODEL)),
                ("views", models.ManyToManyField(blank=True, related_name="faq_views", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
