# Generated by Django 4.2.8 on 2024-01-14 07:28

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownfield.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shop", "0004_category_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                (
                    "content",
                    markdownfield.models.MarkdownField(
                        blank=True, null=True, rendered_field="rendered_content", verbose_name="Content"
                    ),
                ),
                ("rendered_content", markdownfield.models.RenderedMarkdownField(null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("publish", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Publish")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("publish", "Publish")], max_length=10, verbose_name="Status"
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="blog/%Y/%m/%d", verbose_name="Image")),
                ("featured", models.BooleanField(default=False, verbose_name="Featured")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to="shop.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "dislikes",
                    models.ManyToManyField(blank=True, related_name="blog_dislikes", to=settings.AUTH_USER_MODEL),
                ),
                ("likes", models.ManyToManyField(blank=True, related_name="blog_likes", to=settings.AUTH_USER_MODEL)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="blog_products", to="shop.product", verbose_name="Products"
                    ),
                ),
                ("related", models.ManyToManyField(blank=True, to="blog.blogpost", verbose_name="Related posts")),
                ("views", models.ManyToManyField(blank=True, related_name="blog_views", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
                "ordering": ("-publish",),
            },
        ),
    ]
