# Generated by Django 4.2.9 on 2024-01-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_user_last_name_user_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="Phone"),
        ),
    ]
