# Generated by Django 4.2.9 on 2024-01-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
