# Generated by Django 4.2.9 on 2024-01-14 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0002_order_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created",)},
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="shop.cart"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="dislikes",
            field=models.ManyToManyField(blank=True, related_name="dislikes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="product",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.ManyToManyField(blank=True, related_name="views", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, null=True)),
                (
                    "dislikes",
                    models.ManyToManyField(blank=True, related_name="comment_dislikes", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "likes",
                    models.ManyToManyField(blank=True, related_name="comment_likes", to=settings.AUTH_USER_MODEL),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.product")),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="shop.comment",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
