# Generated by Django 4.2.8 on 2024-01-14 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_category_parent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
