# Generated by Django 4.2.9 on 2024-01-19 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_product_comments_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_id",
        ),
    ]
