# Generated by Django 4.2.8 on 2024-01-14 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reply",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
